SELECT RESULT.CLASSID AS ClassId,
	RESULT.CLASSNAME AS ClassName,
	SUM(CASE RESULT.CNT
	WHEN 2016 THEN RESULT.number
	ELSE 0
	END) AS CNT2016,

	SUM(CASE RESULT.CNT
	WHEN 2017 THEN RESULT.number
	ELSE 0
	END ) AS CNT2017,

	SUM(CASE RESULT.CNT
	WHEN 2018 THEN RESULT.number
	ELSE 0
	END ) AS CNT2018,

	SUM(CASE RESULT.CNT
	WHEN 2019 THEN RESULT.number
	ELSE 0
	END ) AS CNT2019
	
FROM (SELECT BD.BOOK_CLASS_ID AS CLASSID,
			BC.BOOK_CLASS_NAME AS CLASSNAME,
			YEAR(BLR.LEND_DATE) AS CNT,
			COUNT(YEAR(BLR.LEND_DATE)) AS NUMBER

	FROM BOOK_LEND_RECORD AS BLR
	LEFT JOIN BOOK_DATA   AS BD
		ON BD.BOOK_ID = BLR.BOOK_ID
	LEFT JOIN BOOK_CLASS AS BC
		ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
	GROUP BY YEAR(BLR.LEND_DATE),BD.BOOK_CLASS_ID,BC.BOOK_CLASS_NAME) AS RESULT

GROUP BY  RESULT.CLASSID,RESULT.CLASSNAME
ORDER BY  RESULT.CLASSID
