SELECT  RESULT.Seq,
		RESULT.BookClass,
		RESULT.BOOK_ID AS BookId,
		RESULT.BookName,
		RESULT.Cnt
FROM (	SELECT	ROW_NUMBER()OVER(PARTITION BY BC.BOOK_CLASS_NAME ORDER BY COUNT(BD.BOOK_ID)DESC)AS Seq,
				BD.BOOK_NAME AS BookName,
				BC.BOOK_CLASS_NAME AS BookClass,
				BD.BOOK_ID,
				COUNT(BD.BOOK_ID) AS Cnt
		FROM BOOK_LEND_RECORD AS BLR
		LEFT JOIN BOOK_DATA   AS BD
			ON BD.BOOK_ID = BLR.BOOK_ID
		LEFT JOIN BOOK_CLASS AS BC
			ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
		GROUP BY BD.BOOK_NAME,BD.BOOK_ID,BC.BOOK_CLASS_NAME) AS RESULT
WHERE RESULT.SEQ <=3
ORDER BY  RESULT.BOOKCLASS,RESULT.CNT DESC, RESULT.BOOK_ID
